#!/usr/bin/env python
# -*- coding: utf-8 -*-

import re

def ipa_creation(word):
    word = re.sub(r"ਫ਼", "f", word)
    word = re.sub(r"ਕ਼", "q", word)
    word = re.sub(r"ਸ਼", "ʃ", word)
    word = re.sub(r"ਖ਼", "x", word)
    word = re.sub(r"ਗ਼", "ɣ", word)
    word = re.sub(r"ਜ਼", "z", word)
    word = re.sub(r"ਪਾ", "ɑː", word)
    word = re.sub(r"ਪੇ", "eː", word)
    word = re.sub(r"ਪੈ", "ɛː", word)
    word = re.sub(r"ਪੀ", "iː", word)
    word = re.sub(r"ਪਿ", "ɪ", word)
    word = re.sub(r"ਪੋ", "oː", word)
    word = re.sub(r"ਪੌ", "ɔː", word)
    word = re.sub(r"ਪੂ", "uː", word)
    word = re.sub(r"ਪੁ", "ʊ", word)
    word = re.sub(r"੍ਰ", "ʳ", word)
    word = re.sub(r"੍ਹ", "ʰ", word)
    word = re.sub(r"ਬ", "b", word)
    word = re.sub(r"ਭ", "bʰ", word)
    word = re.sub(r"ਦ", "d", word)
    word = re.sub(r"ਧ", "dʰ", word)
    word = re.sub(r"ਡ", "ɖ", word)
    word = re.sub(r"ਢ", "ɖʰ", word)
    word = re.sub(r"ਜ", "j", word)
    word = re.sub(r"ਝ", "jʰ", word)
    word = re.sub(r"ਗ", "ɡ", word)
    word = re.sub(r"ਘ", "gʰ", word)
    word = re.sub(r"ਹ", "h", word)
    word = re.sub(r"ਯ", "y", word)
    word = re.sub(r"ਕ", "k", word)
    word = re.sub(r"ਖ", "kʰ", word)
    word = re.sub(r"ਲ", "l", word)
    word = re.sub(r"ਮ", "m", word)
    word = re.sub(r"ਨ", "n", word)
    word = re.sub(r"ਣ", "ɳ", word)
    word = re.sub(r"ं", "ŋ", word)
    word = re.sub(r"ਂ", "ŋ", word)
    word = re.sub(r"ਪ", "p", word)
    word = re.sub(r"ਫ", "pʰ", word)
    word = re.sub(r"ਰ", "r", word)
    word = re.sub(r"ੜ", "ɽ", word)
    word = re.sub(r"ੜ੍ਹ", "ɽʱ", word)
    word = re.sub(r"ਸ", "s", word)
    word = re.sub(r"ਤ", "t", word)
    word = re.sub(r"ਥ", "tʰ", word)
    word = re.sub(r"ਟ", "ʈ", word)
    word = re.sub(r"ਠ", "ʈʰ", word)
    word = re.sub(r"ਚ", "c", word)
    word = re.sub(r"ਛ", "cʰ", word)
    word = re.sub(r"ਵ", "v", word)
    word = re.sub(r"ਆ", "ɑː", word)
    word = re.sub(r"ਏ", "eː", word)
    word = re.sub(r"ਐ", "ɛː", word)
    word = re.sub(r"ਅ", "ə", word)
    word = re.sub(r"ਈ", "iː", word)
    word = re.sub(r"ਇ", "ɪ", word)
    word = re.sub(r"ਓ", "oː", word)
    word = re.sub(r"ਔ", "ɔː", word)
    word = re.sub(r"ਊ", "uː", word)
    word = re.sub(r"ਉ", "ʊ", word)
    word = re.sub(r"ੰ", " ̃", word)
    word = re.sub(r"ਿ", "ɪ", word)
    word = re.sub(r"ੀ", "iː", word)
    word = re.sub(r"ੇ", "eː", word)
    word = re.sub(r"ੈ", "ɛː", word)
    word = re.sub(r"ੋ", "oː", word)
    word = re.sub(r"ੌ", "ɔː", word)
    word = re.sub(r"ਾ", "ɑː", word)
    word = re.sub(r"ੁ", "ʊ", word)
    word = re.sub(r"ੂ", "uː", word)
    word = re.sub(r"ੱ", "a", word)
    return word

