#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
DEVELOPER: GURJOT SINGH MAHI
E-MAIL: GURJOTMAHI28@GMAIL.COM
WRITTEN USING: PYTHON 3.6

THE PUNJABI IPA CONVERSION SOFTWARE PROVIDE THE CAPABILITY TO CONVERT THE
PUNJABI WORDS OR CHARACTERS TO ITS EQUIVALENT IPA CHARACTERS.

THIS PIECE OF CODE WAS WRITTEN AS A UTILITY, DURING WRITING MY RESEARCH PAPER
WHERE I HAVE TO DEAL WITH LOT OF PUNJABI WORDS AND HAVE TO MENTION ITS EQUIVALENT
IPA FORMAT WORDS

I HOPE THIS WILL HELP MY FELLOW RESEARCHERS AND OTHER PEOPLE AS A UTILITY
WHO WISH TO CONVERT PUNJABI CHARACTER TO IPA IN WRITING
"""

import os
from tkinter import *
from main_window import window

root = Tk()
root.geometry("1000x600+30+60")
imgicon = PhotoImage(file=os.path.join('pipalogo.gif'))
root.tk.call('wm', 'iconphoto', root._w, imgicon)
root.title("PUNJABI IPA CONVERTER")
window(root)
root.mainloop()
